grant usage on schema public to authenticated, service_role;
grant select on public.board_profiles to authenticated;
grant select, insert, update, delete on public.board_tasks to authenticated;
grant select, insert, update, delete on public.board_task_comments to authenticated;
grant select, insert, update, delete on public.board_calendar_events to authenticated;
grant select, insert, update, delete on public.board_notes to authenticated;
grant select, insert, update, delete on public.board_announcements to authenticated;
grant select, insert, update, delete on public.board_chat_messages to authenticated;
grant select, insert, update, delete on public.board_attachments to authenticated;
grant select, insert on public.board_activity_log to authenticated;
grant all on public.board_profiles to service_role;
grant all on public.board_tasks to service_role;
grant all on public.board_task_comments to service_role;
grant all on public.board_calendar_events to service_role;
grant all on public.board_notes to service_role;
grant all on public.board_announcements to service_role;
grant all on public.board_chat_messages to service_role;
grant all on public.board_attachments to service_role;
grant all on public.board_activity_log to service_role;
